// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASRDXyRPgAinhzrNDV9eTFqQsx-RHtXgQ',
    appId: '1:1043739333910:android:9f40f5da4e2737acc7ac37',
    messagingSenderId: '1043739333910',
    projectId: 'evetick-a2d16',
    storageBucket: 'evetick-a2d16.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkOvjSVWRGw994Er5LBgjoC4CkUSouVV0',
    appId: '1:1043739333910:ios:c68d8d94c6e04133c7ac37',
    messagingSenderId: '1043739333910',
    projectId: 'evetick-a2d16',
    storageBucket: 'evetick-a2d16.firebasestorage.app',
    androidClientId: '1043739333910-i79d0p2oaj495170opjo166ajkr7vsib.apps.googleusercontent.com',
    iosClientId: '1043739333910-7nermlikk5vd6s3vg3tg5a86mv5ilmgp.apps.googleusercontent.com',
    iosBundleId: 'com.example.evetickOrganizer',
  );
}
